module ClassVisits exposing (page)

import Bootstrap.Button as Button
import Bootstrap.Card as Card
import Bootstrap.Card.Block as Block
import Bootstrap.Grid as Grid
import Bootstrap.Grid.Col as Col
import Bootstrap.Grid.Row as Row
import Bootstrap.ListGroup as Listgroup
import Bootstrap.Navbar as Navbar
import Bootstrap.Utilities.Spacing as Spacing
import Browser exposing (UrlRequest)
import Browser.Navigation as Navigation
import Html exposing (..)
import Html.Attributes exposing (..)
import Html.Events exposing (onClick)
import Model exposing (Model, Msg(..))
import Url exposing (Url)
import Url.Parser as UrlParser exposing ((</>), Parser, s, top)


page : Model -> List (Html Msg)
page model =
    [ h1 [ Spacing.my5 ] [ text "What We Will Do Again when COVID-19 is Over" ]
    , Grid.row []
        [ Grid.col []
            [ img [ style "width" "300px", src "img/whatwedo1.png" ] []
            ]
        , Grid.col [ Col.lg8, Col.middleMd ]
            [ text "At Software: Tool For Change, we provide elementary and middle school students with a fun and safe environment to learn code. We incorporate mathematical concepts such as the cartesian coordinate system and trigonometry. We have seen students understand things that they have learned in class better by playing with the tools we have provided."
            ]
        ]
    , Grid.row []
        [ Grid.col []
            [ h2 [ Spacing.mt5 ] [ text "Activities" ]
            ]
        ]
    , Grid.row []
        [ Grid.col []
            [ img [ style "width" "300px", src "img/LoveTheEarth.png" ] [] ]
        , Grid.col [ Col.md8 ]
            [ Card.config []
                |> Card.headerH3 [ style "color" "crimson", style "font-weight" "700" ] [ text "Telling Stories with Code" ]
                |> Card.block []
                    [ Block.text [] [ text "This is a new idea we developed with Principal De Tullio (now at St Luke).  The idea is to take two things children find hard (math and creative writing) and put them together into a fun activity.  Each group of four children created spent three hours, spread over two days creating a short narrative and animating it in the form of an eight-frame comic.  Even in such a sort span of time, two groups made remarkable progress.  Open them in new taps, and click on the frames to see the animations." ]
                    , Block.link [ href "https://macoutreach.rocks/comic0/" ] [ text "I Need Help." ]
                    , Block.link [ href "https://macoutreach.rocks/comic1/" ] [ text "Love the Earth." ]
                    ]
                |> Card.view
            ]
        ]
    , Grid.row []
        [ Grid.col []
            [ img [ style "width" "300px", src "img/binary-blast-off.png" ] [] ]
        , Grid.col [ Col.md8 ]
            [ Card.config []
                |> Card.headerH3 [ style "color" "crimson", style "font-weight" "700" ] [ text "Binary Blast-off" ]
                |> Card.block []
                    [ Block.text [ style "font-weight" "600", style "font-size" "20px" ] [ text "Activity Description" ]
                    , Block.text [] [ text "We will need 5 volunteers to play the role of binary digits, or bits, and help us count, which will lead to a surprising result." ]
                    , Block.text [ style "font-weight" "600", style "font-size" "20px" ] [ text "Expected Outcomes" ]
                    , Block.text [] [ text "Zeros and Ones are the basis for computation in computers, and the system of numbers is called binary." ]
                    , Block.text [ style "font-weight" "600", style "font-size" "20px" ] [ text "Pre-Trip Prep" ]
                    , Block.text [] [ text "We have found that the hands-on approach works without preparation." ]
                    , Block.text [ style "font-weight" "600", style "font-size" "20px" ] [ text "Post-Trip Reinforcement" ]
                    , Block.text [] [ text "After the trip, it would be useful to show how numbers can be represented in different bases, including decimal and binary, and show how long addition works the same way in different bases." ]
                    , Block.text [ style "font-weight" "600", style "font-size" "20px" ] [ text "Time Needed" ]
                    , Block.text [] [ text "20 - 30 minutes" ]
                    ]
                |> Card.view
            ]
        ]
    , Grid.row []
        [ Grid.col []
            [ img [ style "width" "300px", src "img/image2bits.png" ] [] ]
        , Grid.col [ Col.md8 ]
            [ Card.config []
                |> Card.headerH3 [ style "color" "crimson", style "font-weight" "700" ] [ text "Image 2 Bits" ]
                |> Card.block []
                    [ Block.text [ style "font-weight" "600", style "font-size" "20px" ] [ text "Activity Description" ]
                    , Block.text [] [ text "Having seen binary numbers, we will now use an iPad game to show that pictures are encoded using binary numbers. Each child will create a black-and-white image and share it wirelessly with the other iPads, after which they will try to use their knowledge of binary to decode the images. It is quite possible to decode the images by guessing, but it is faster when some tricks are discovered based on understanding how numbers are represented (i.e. digit values grow from right to left, so it is easier to try “turning on” bigits from left to right, since once the bigits to the left are known, turning on the next bigit will either put the number over or not). Even kids who think they are not good at math usually figure this out in the context of the game, but we try to help the small number who need a bit of extra encouragement." ]
                    , Block.text [ style "font-weight" "600", style "font-size" "20px" ] [ text "Expected Outcomes" ]
                    , Block.text [] [ text "All information we share or process digitally is encoded as binary numbers. Knowing the code, we can even decode small examples." ]
                    , Block.text [ style "font-weight" "600", style "font-size" "20px" ] [ text "Pre-Trip Prep" ]
                    , Block.text [] [ text "Binary means base 2. They do not need to know this, but if they know about different bases, this will put it in context. Knowing the powers of 2 (1,2,4,8,16,32,64,128) will help them." ]
                    , Block.text [ style "font-weight" "600", style "font-size" "20px" ] [ text "Post-Trip Reinforcement" ]
                    , Block.text [] [ text "For classrooms with iPads, we have another app which shows how colour pictures are encoded, and allows the images to be edited by changing the numbers corresponding to pixel values." ]
                    , Block.text [ style "font-weight" "600", style "font-size" "20px" ] [ text "Time Needed" ]
                    , Block.text [] [ text "20 - 60 minutes. They can learn how to do the binary decoding in 20 min, and if you have it on your iPads, they can come back to this whenever they have 10 minutes left over at the end of a period." ]
                    ]
                |> Card.view
            ]
        ]
    , Grid.row []
        [ Grid.col []
            [ img [ style "width" "300px", src "img/CAT-scan.png" ] [] ]
        , Grid.col [ Col.md8 ]
            [ Card.config []
                |> Card.headerH3 [ style "color" "crimson", style "font-weight" "700" ] [ text "CAT Scan (stand up activity)" ]
                |> Card.block []
                    [ Block.text [ style "font-weight" "600", style "font-size" "20px" ] [ text "Activity Description" ]
                    , Block.text [] [ text "Kids and supervisors will play the role of a dog’s stomach and a missing gold coin, as we try to figure out how to locate the coin using x-rays from multiple directions. If we are efficient, we can go on to decode the positions of bones and other tissues in the body. The computer in this case will be a whiteboard." ]
                    , Block.text [ style "font-weight" "600", style "font-size" "20px" ] [ text "Expected Outcomes" ]
                    , Block.text [] [ text "An algorithm is a precise list of instructions, and even kids can figure one out. Some problems involve so much data, we need computers to solve them, in this case giving us a powerful medical tool." ]
                    , Block.text [ style "font-weight" "600", style "font-size" "20px" ] [ text "Pre-Trip Prep" ]
                    , Block.text [] [ text "It would be helpful if the kids were reminded that light goes in straight lines and that there are kinds of light we cannot see, like x-rays. Doing SUDOKU problems in class will prime them for the type of logic they will need, and help them discover a workable algorithm themselves. We need to add the fractions 1,1/2,1/4,1/8,1/16, so it might be worth practicing these." ]
                    , Block.text [ style "font-weight" "600", style "font-size" "20px" ] [ text "Post-Trip Reinforcement" ]
                    , Block.text [] [ text "As a class or group activity, kids who previously did SUDOKU puzzles could try to write an algorithm (a step-bystep list of instructions) for solving a SUDOKU puzzle. Kids you need to keep busy for a couple of weeks could be asked to write an ELM program to solve SUDOKU puzzles." ]
                    , Block.text [ style "font-weight" "600", style "font-size" "20px" ] [ text "Time Needed" ]
                    , Block.text [] [ text "20 min to 25 min per group of up to 16. Need a flip-chart, whiteboard or smart-board, and some separation from other children to prevent a feedback loop of talking over the other group." ]
                    ]
                |> Card.view
            ]
        ]
    , Grid.row []
        [ Grid.col []
            [ img [ style "width" "300px", src "img/Word1.png" ] [] ]
        , Grid.col [ Col.md8 ]
            [ Card.config []
                |> Card.headerH3 [ style "color" "crimson", style "font-weight" "700" ] [ text "ElmJr App" ]
                |> Card.block []
                    [ Block.text [ style "font-weight" "600", style "font-size" "20px" ] [ text "Activity Description" ]
                    , Block.text [] [ text "Using a iPad app called ElmJr we will help kids to create graphics and animations, starting with some common challenges, but going on to whatever they can imagine." ]
                    , Block.text [ style "font-weight" "600", style "font-size" "20px" ] [ text "Expected Outcomes" ]
                    , Block.text [] [ text "They will learn to write error free programs in Elm programming language, focussing on graphics, and animation for students who want a challenge." ]
                    , Block.text [ style "font-weight" "600", style "font-size" "20px" ] [ text "Pre-Trip Prep" ]
                    , Block.text [] [ text "ElmJr app should be installed on their iPads. They will have a lot of choice in creating computer graphics in this activity, but if they are familiar with (x,y) coordinates, and with graphs of simple functions, they will have the widest range of possibilities." ]
                    , Block.text [ style "font-weight" "600", style "font-size" "20px" ] [ text "Post-Trip Reinforcement" ]
                    , Block.text [] [ text "Since ElmJr app is a free iPad app, they can continue to work on animations on their own even at home." ]
                    , Block.text [ style "font-weight" "600", style "font-size" "20px" ] [ text "Time Needed" ]
                    , Block.text [] [ text "We would like to have 2 hours with each class. For scheduling, it would be convenient for me to send two instructors for the day, and have them each visit one class in the morning and one in the afternoon. In addition to the instructor, we should have a few undergrad volunteers who can float between classes to help fix errors, or formulate statements correctly." ]
                    ]
                |> Card.view
            ]
        ]
    , Grid.row []
        [ Grid.col []
            [ img [ style "width" "300px", src "img/binary-blast-off.png" ] [] ]
        , Grid.col [ Col.md8 ]
            [ Card.config []
                |> Card.headerH3 [ style "color" "crimson", style "font-weight" "700" ] [ text "Elm Graphics" ]
                |> Card.block []
                    [ Block.text [ style "font-weight" "600", style "font-size" "20px" ] [ text "Activity Description" ]
                    , Block.text [] [ text "Using a web-based programming language we will all create graphics and animations, starting with some common challenges, but going on to whatever they can imagine." ]
                    , Block.text [ style "font-weight" "600", style "font-size" "20px" ] [ text "Expected Outcomes" ]
                    , Block.text [] [ text "They will learn to write programs in a programming language, focussing on graphics, and animation for students who want a challenge." ]
                    , Block.text [ style "font-weight" "600", style "font-size" "20px" ] [ text "Pre-Trip Prep" ]
                    , Block.text [] [ text "They will have a lot of choice in creating computer graphics in this activity, but if they are familiar with (x,y) coordinates, and with graphs of simple functions, they will have the widest range of possibilities." ]
                    , Block.text [ style "font-weight" "600", style "font-size" "20px" ] [ text "Post-Trip Reinforcement" ]
                    , Block.text [] [ text "Because there is nothing to install, they can continue to work on animations on their own or in groups." ]
                    , Block.text [ style "font-weight" "600", style "font-size" "20px" ] [ text "Time Needed" ]
                    , Block.text [] [ text "We would like to have 2 hours with each class. For scheduling, it would be convenient for me to send two instructors for the day, and have them each visit one class in the morning and one in the afternoon. In addition to the instructor, we should have a few undergrad volunteers who can float between classes to help fix errors, or formulate statements correctly." ]
                    ]
                |> Card.view
            ]
        ]
    , Grid.row []
        [ Grid.col []
            [ img [ style "width" "300px", src "img/venture.png" ] [] ]
        , Grid.col [ Col.md8 ]
            [ Card.config []
                |> Card.headerH3 [ style "color" "crimson", style "font-weight" "700" ] [ text "MacVenture" ]
                |> Card.block []
                    [ Block.text [ style "font-weight" "600", style "font-size" "20px" ] [ text "Activity Description" ]
                    , Block.text [] [ text "Pairs or triples of students will use tap and drag operations to create an adventure game, and they will see the structure of the game as a graph, and that some aspects of the game (such as whether it is impossible) can be decoded by examining the graph. We will also take a first look at adding functionality using a text language (like Python used in the pyVenture activity)." ]
                    , Block.text [ style "font-weight" "600", style "font-size" "20px" ] [ text "Expected Outcomes" ]
                    , Block.text [] [ text "A computer science graph is a set of points with a set of edges (lines) connecting them. It is probably the most important tool we have for representing information (such as the graph of Facebook friends!)." ]
                    , Block.text [ style "font-weight" "600", style "font-size" "20px" ] [ text "Pre-Trip Prep" ]
                    , Block.text [] [ text "If you have studied a literary form (like haiku or the sonnet), they can write their adventure in this form, and you can suggest it as a challenge." ]
                    , Block.text [ style "font-weight" "600", style "font-size" "20px" ] [ text "Post-Trip Reinforcement" ]
                    , Block.text [] [ text "There are many other examples of graphs, and the class should be able to come up with some examples. For fun, they could, on the board, draw the graph of who often eats lunch with whom. They could also use the internet to figure out which airports in Canada (or the World!) are connected by direct flights." ]
                    , Block.text [ style "font-weight" "600", style "font-size" "20px" ] [ text "Time Needed" ]
                    , Block.text [] [ text "50 min to 120 min. They need about 15 minutes to understand the basics, but few can finish a playable game in under 50 minutes. The good creative writers won’t want to stop, but some children will need goals, such as creating 6 places in their game, or 6 keys, or creating 2 dead-ends, etc." ]
                    ]
                |> Card.view
            ]
        ]
    , Grid.row []
        [ Grid.col []
            [ img [ style "width" "300px", src "img/information-revolution.png" ] [] ]
        , Grid.col [ Col.md8 ]
            [ Card.config []
                |> Card.headerH3 [ style "color" "crimson", style "font-weight" "700" ] [ text "Information Revolution (group discussion)" ]
                |> Card.block []
                    [ Block.text [ style "font-weight" "600", style "font-size" "20px" ] [ text "Activity Description" ]
                    , Block.text [] [ text "The Information Revolution, also called the Digital Revolution and the Data Revolution is about the changes software is having on all aspects of our lives, from how we work, play and keep in touch with friends and families. We want to hear about what they see as the problems (e.g. cyberbullying, loss of privacy, undermining democracy) and opportunities (e.g. exciting new jobs and new ways to better share scarce food and other resources). We will present forecasts on the expected explosion of jobs in this area." ]
                    , Block.text [ style "font-weight" "600", style "font-size" "20px" ] [ text "Expected Outcomes" ]
                    , Block.text [] [ text "The kids will start to think about the types and pace of change, and how we have choices as society and individuals about how we react to this change." ]
                    , Block.text [ style "font-weight" "600", style "font-size" "20px" ] [ text "Pre-Trip Prep" ]
                    , Block.text [] [ text "To prime the kids for this event, it would be helpful if you discuss past revolutions, and how some, like the Industrial Revolution are caused by new inventions, and others, like the Renaissance, are about new ideas." ]
                    , Block.text [ style "font-weight" "600", style "font-size" "20px" ] [ text "Post-Trip Reinforcement" ]
                    , Block.text [] [ text "A post-trip writing assignment would reinforce the discussion, with topics such as: Does cyberbullying have a solution in new software features, new laws or better awareness of bullying? Could networked information be used to reduce food waste and solve hunger in Canada?" ]
                    , Block.text [ style "font-weight" "600", style "font-size" "20px" ] [ text "Time Needed" ]
                    , Block.text [] [ text "20 - 30 minutes" ]
                    ]
                |> Card.view
            ]
        ]
    , Grid.row []
        [ Grid.col []
            [ img [ style "width" "300px", src "img/Design-Thinking.jpg" ] [] ]
        , Grid.col [ Col.md8 ]
            [ Card.config []
                |> Card.headerH3 [ style "color" "crimson", style "font-weight" "700" ] [ text "Design Thinking" ]
                |> Card.block []
                    [ Block.text [ style "font-weight" "600", style "font-size" "20px" ] [ text "Activity Description" ]
                    , Block.text [] [ text " Although technical literacy and skill is important, it is necessary we learn how to use it in a way that benefits users most. We teach the Design Thinking method to students to help them design apps with a user-centered approach. We teach this workshops to kids from grade 6-8 and their objective is to help kids in grade 1-2 that struggle with math. These workshops require the students to empathize, ideate and interview with a given problem a grade 1-2 is having." ]
                    , Block.text [ style "font-weight" "600", style "font-size" "20px" ] [ text "Expected Outcomes" ]
                    , Block.text [] [ text " After the Design-Thinking Workshop, the kids will have a better understanding of how to design tools that assist users with addressing some problem. After completing the workshop they will have a prototype app or game which aims to solve some problem. " ]
                    , Block.text [ style "font-weight" "600", style "font-size" "20px" ] [ text "Pre-Trip Prep" ]
                    , Block.text [] [ text " Preparing for this workshop might include helping students improve their interviewing skills. What also may help is giving them a brief overview of the Design Thinking process. Exercises in empathizing and understanding perspectives of others would be helpful. " ]
                    , Block.text [ style "font-weight" "600", style "font-size" "20px" ] [ text "Post-Trip Reinforcement" ]
                    , Block.text [] [ text " Since the Design-Thinking process will result in some prototype, allowing them to continue to work on their project and bring it to life would be a great way to show the students the effectiveness of Design Thinking." ]
                    , Block.text [ style "font-weight" "600", style "font-size" "20px" ] [ text "Time Needed" ]
                    , Block.text [] [ text " The workshop can take 1-3 school days, teachers can select desired length." ]
                    ]
                |> Card.view
            ]
        ]
    , Grid.row []
        -- empty row
        [ Grid.col []
            [ h1 [] [ text " " ]
            ]
        ]
    , Grid.row [ Row.attrs [ style "background-color" "rgb(52,58,64)" ] ]
        -- grey space
        [ Grid.col []
            [ h1 [] [ text " " ]
            ]
        ]
    ]
